---
- name: Uninstall httpd
  hosts: all
  become: true
  tasks: 
    - name: stop the service
      service:
        name: httpd
        state: stopped

    - name: uninstall httpd
      yum:
         name: httpd
         state: removed
  
